[package]
name = "tari_bor"
description = "The binary object representation (BOR) crate provides a binary encoding for template/engine data types"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# git rev: include fix from https://github.com/enarx/ciborium/pull/80
ciborium = { git = "https://github.com/enarx/ciborium.git", rev = "114614d2a61102eb2321c68e53799d1e6f087aef", default-features = false }
ciborium-io = { git = "https://github.com/enarx/ciborium.git", rev = "114614d2a61102eb2321c68e53799d1e6f087aef", default-features = false }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }

[dev-dependencies]
serde_json = "1.0"

[features]
default = ["std"]
std = ["ciborium/std", "serde/std"]
alloc = ["serde/alloc", "ciborium-io/alloc"]
json_encoding = []

