[package]
name = "tari_state_store_sqlite"
description = "The Tari DAN wallet daemon"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
tari_dan_storage = { workspace = true }
tari_dan_common_types = { workspace = true }
tari_transaction = { workspace = true }
# TODO: needed for FixedHash
tari_common_types = { workspace = true }

anyhow = "1.0"
bigdecimal = "0.4.1"
diesel = { version = "2", default-features = false, features = ["sqlite", "time", "numeric"] }
diesel_migrations = "2"
log = "0.4"
hex = "0.4"
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
time = "0.3"

[dev-dependencies]
rand = "0.8"