[package]
name = "tari_dan_storage"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tari_common_types = { workspace = true }
tari_dan_common_types = { workspace = true }

# Shard store deps
tari_engine_types = { workspace = true }
tari_transaction = { workspace = true }
tari_core = { workspace = true }
tari_mmr = { workspace = true }
tari_crypto = { workspace = true }

anyhow = "1.0"
chrono = "0.4.23"
log = "0.4"
rand = "0.8"
thiserror = "1"
serde = "1.0"
time = { version = "0.3", features = ["serde"] }
