[package]
name = "tari_epoch_manager"
description = "The Tari epoch manager"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
tari_core = { workspace = true }
tari_common_types = { workspace = true }
tari_shutdown = { workspace = true }
tari_dan_common_types = { workspace = true }
tari_comms = { workspace = true, optional = true }
tari_dan_storage = { workspace = true }
tari_dan_storage_sqlite = { workspace = true, optional = true }
tari_base_node_client = { workspace = true, optional = true }
tari_crypto = { workspace = true }
tari_mmr = { workspace = true, optional = true }

anyhow = "1.0"
async-trait = "0.1"
log = { version = "0.4", optional = true }
thiserror = "1.0"
tokio = { version = "1", default-features = false, features = ["sync"] }

[features]
base_layer = [
  "log",
  "tari_base_node_client",
  "tari_comms",
  "tari_dan_storage_sqlite",
  "tari_mmr",
]
