[package]
name = "tari_state_store_rocksdb"
description = "RocksDB implementation of Tari state store"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# TODO: needed for FixedHash
tari_common_types = { workspace = true }
tari_dan_storage = { workspace = true }
tari_dan_common_types = { workspace = true }
tari_transaction = { workspace = true }
tari_engine_types = { workspace = true }
tari_state_tree = { workspace = true }
tari_utilities = { workspace = true }

anyhow = { workspace = true }
bigdecimal = { workspace = true }
indexmap = { workspace = true }
log = { workspace = true }
hex = { workspace = true }
rocksdb = { workspace = true }
serde = { workspace = true, default-features = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
tempfile = { workspace = true }