[package]
name = "tari_rpc_macros"
description = "RPC service proc macro"
repository = "https://github.com/tari-project/tari"
homepage = "https://tari.com"
readme = "README.md"
version = "0.53.0-dan.0"
edition = "2018"
license.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["fold"] }

#[dev-dependencies]
#tari_comms = {  path = "../core", features = ["rpc"] }
#tari_test_utils = {  path = "../../infrastructure/test_utils" }

#futures = "0.3.5"
#prost = "0.12.0"
#tokio = { version = "1", features = ["macros"] }
#tower-service = "0.3"
