[package]
name = "transaction_generator"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
tari_template_lib = { workspace = true }
tari_transaction = { workspace = true }
tari_engine_types = { workspace = true }
tari_template_builtin = { workspace = true }
tari_crypto = { workspace = true }

anyhow = "1.0.72"
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
bytes = "0.4"
clap = { version = "4.3.21", features = ["derive"] }
rayon = "1.7.0"
rand = "0.8"
once_cell = { version = "1.18.0", features = ["critical-section"] }

[package.metadata.cargo-machete]
ignored = [
    # Need to force critical_section feature
    "once_cell",
]
