[package]
name = "tari_template_lib"
description = "Tari template library provides abstrations that interface with the Tari validator engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
tari_template_abi = { workspace = true }
tari_template_macros = { workspace = true, optional = true }
tari_bor = { workspace = true, default-features = false }

newtype-ops = "0.1.4"
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
serde-byte-array = "0.1.2"

[dev-dependencies]
serde_json = "1.0"

[features]
default = ["macro", "std"]
macro = ["tari_template_macros"]
std = ["serde/std", "tari_bor/std"]
