[package]
name = "tari_dan_storage_lmdb"
description = "LMDB implementation of the Tari Storage API"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
tari_bor = { workspace = true }
tari_dan_engine = { workspace = true }
tari_dan_common_types = { workspace = true }
tari_storage = { workspace = true }

lmdb-zero = "0.4.4"
hex = "0.4.3"
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }

[dev-dependencies]
tempfile = "3.3.0"
