[package]
name = "tari_indexer"
authors = ["The Tari Development Community"]
description = "The Tari DAN indexer implementation"
repository = "https://github.com/tari-project/tari"
license = "BSD-3-Clause"
version = "0.35.1"
edition = "2018"

[dependencies]
tari_engine_types = { path = "../../dan_layer/engine_types" }
tari_template_lib = { path = "../../dan_layer/template_lib" }

clap = { version = "3.2.22", features = ["derive", "env"] }