[package]
name = "tari_indexer"
authors = ["The Tari Development Community"]
description = "The Tari DAN indexer implementation"
repository = "https://github.com/tari-project/tari"
license = "BSD-3-Clause"
version = "0.35.1"
edition = "2018"

[dependencies]
tari_common = { git = "https://github.com/tari-project/tari.git", branch = "development", package = "tari_common" }
tari_shutdown = { git = "https://github.com/tari-project/tari.git", branch = "development", package = "tari_shutdown" }

tari_engine_types = { path = "../../dan_layer/engine_types" }
tari_template_lib = { path = "../../dan_layer/template_lib" }

clap = { version = "3.2.22", features = ["derive", "env"] }
log = { version = "0.4.8", features = ["std"] }
tokio = { version = "1.10", features = ["macros", "time", "sync", "rt-multi-thread"] }